package com.last.year.project.bean;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin", catalog = "searchy")
public class Admin implements java.io.Serializable {

	private String username;
	private String password;
	private String email;
	private boolean enabled;
	private Set<Atm> atms = new HashSet<Atm>(0);
	
	private Set<Authorities> authoritieses = new HashSet<Authorities>(0);
	private Set<Bank> banks = new HashSet<Bank>(0);

	public Admin() {
	}

	public Admin(String username, boolean enabled) {
		this.username = username;
		this.enabled = enabled;
	}

	public Admin(String username, String password, String email,
			boolean enable, Set<Atm> atms, Set<Authorities> authoritieses,
			Set<Bank> banks) {
		this.username = username;
		this.password = password;
		this.email = email;
		this.enabled = enabled;
		this.atms = atms;
		this.authoritieses = authoritieses;
		this.banks = banks;
	}

	@Id
	@Column(name = "username", unique = true, nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnable() {
		return this.enabled;
	}

	public void setEnable(boolean enabled) {
		this.enabled = enabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admin")
	public Set<Atm> getAtms() {
		return this.atms;
	}

	public void setAtms(Set<Atm> atms) {
		this.atms = atms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admin")
	public Set<Authorities> getAuthoritieses() {
		return this.authoritieses;
	}

	public void setAuthoritieses(Set<Authorities> authoritieses) {
		this.authoritieses = authoritieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admin")
	public Set<Bank> getBanks() {
		return this.banks;
	}

	public void setBanks(Set<Bank> banks) {
		this.banks = banks;
	}

}
