package com.last.year.project.bean;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Atm generated by hbm2java
 */
@Entity
@Table(name = "atm", catalog = "searchy")
public class Atm implements java.io.Serializable {

	private int idAtm;
	private Admin admin;
	private Bank bank;
	private String name;
	private String geolocation;
	private String address;
	private String company;
	private Double distance;
	

	private Set<Geofencing> geofencings = new HashSet<Geofencing>(0);

	public Atm() {
	}

	public Atm(int idAtm, Admin admin, Bank bank) {
		this.idAtm = idAtm;
		this.admin = admin;
		this.bank = bank;
	}

	public Atm(int idAtm, Admin admin, Bank bank, String name,
			String geolocation, String address, Set<Geofencing> geofencings,String company) {
		this.idAtm = idAtm;
		this.admin = admin;
		this.bank = bank;
		this.name = name;
		this.geolocation = geolocation;
		this.address = address;
		this.geofencings = geofencings;
		this.company = company;
	}

	@Id
	@Column(name = "idAtm", unique = true, nullable = false)
	public int getIdAtm() {
		return this.idAtm;
	}

	public void setIdAtm(int idAtm) {
		this.idAtm = idAtm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Admin_username", nullable = false)
	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "bank_idbank", nullable = false)
	public Bank getBank() {
		return this.bank;
	}

	public void setBank(Bank bank) {
		this.bank = bank;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "company", length = 45)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "geolocation", length = 45)
	public String getGeolocation() {
		return this.geolocation;
	}

	public void setGeolocation(String geolocation) {
		this.geolocation = geolocation;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
	
	@Column(name = "distance")
	public Double getDistance() {
		return distance;
	}

	public void setDistance(Double distance) {
		this.distance = distance;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "atm")
	public Set<Geofencing> getGeofencings() {
		return this.geofencings;
	}

	public void setGeofencings(Set<Geofencing> geofencings) {
		this.geofencings = geofencings;
	}

}
