package com.last.year.project.bean;

// Generated Sep 12, 2014 7:20:32 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Authorities generated by hbm2java
 */
@Entity
@Table(name = "authorities", catalog = "searchy")
public class Authorities implements java.io.Serializable {

	private String authority;
	private Admin admin;

	public Authorities() {
	}

	public Authorities(String authority, Admin admin) {
		this.authority = authority;
		this.admin = admin;
	}

	@Id
	@Column(name = "authority", unique = true, nullable = false, length = 45)
	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false)
	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

}
