package com.last.year.project.bean;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bank generated by hbm2java
 */
@Entity
@Table(name = "bank", catalog = "searchy")
public class Bank implements java.io.Serializable {

	private int idbank;
	private Admin admin;
	private String name;
	private String address;
	private Set<Atm> atms = new HashSet<Atm>(0);

	public Bank() {
	}

	public Bank(int idbank, Admin admin) {
		this.idbank = idbank;
		this.admin = admin;
	}

	public Bank(int idbank, Admin admin, String name, String address,
			Set<Atm> atms) {
		this.idbank = idbank;
		this.admin = admin;
		this.name = name;
		this.address = address;
		this.atms = atms;
	}

	@Id
	@Column(name = "idbank", unique = true, nullable = false)
	public int getIdbank() {
		return this.idbank;
	}

	public void setIdbank(int idbank) {
		this.idbank = idbank;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Admin_username", nullable = false)
	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bank")
	public Set<Atm> getAtms() {
		return this.atms;
	}

	public void setAtms(Set<Atm> atms) {
		this.atms = atms;
	}

}
