package com.last.year.project.bean;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Geofencing generated by hbm2java
 */
@Entity
@Table(name = "geofencing", catalog = "searchy")
public class Geofencing implements java.io.Serializable {

	private int idGeofencing;
	private Atm atm;
	private User user;
	private Date time;

	public Geofencing() {
	}

	public Geofencing(int idGeofencing, Atm atm, User user) {
		this.idGeofencing = idGeofencing;
		this.atm = atm;
		this.user = user;
	}

	public Geofencing(int idGeofencing, Atm atm, User user, Date time) {
		this.idGeofencing = idGeofencing;
		this.atm = atm;
		this.user = user;
		this.time = time;
	}

	@Id
	@Column(name = "idGeofencing", unique = true, nullable = false)
	public int getIdGeofencing() {
		return this.idGeofencing;
	}

	public void setIdGeofencing(int idGeofencing) {
		this.idGeofencing = idGeofencing;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Atm_idAtm", nullable = false)
	public Atm getAtm() {
		return this.atm;
	}

	public void setAtm(Atm atm) {
		this.atm = atm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_username", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
