package com.last.year.project.bean;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Loging generated by hbm2java
 */
@Entity
@Table(name = "loging", catalog = "searchy")
public class Loging implements java.io.Serializable {

	private int idloging;
	private User user;
	private String deviceId;
	private String deviceNumber;
	private String deviceEmail;
	private String deviceLocation;
	private String query;

	public Loging() {
	}

	public Loging(int idloging, User user) {
		this.idloging = idloging;
		this.user = user;
	}

	public Loging(int idloging, User user, String deviceId,
			String deviceNumber, String deviceEmail, String deviceLocation,
			String query) {
		this.idloging = idloging;
		this.user = user;
		this.deviceId = deviceId;
		this.deviceNumber = deviceNumber;
		this.deviceEmail = deviceEmail;
		this.deviceLocation = deviceLocation;
		this.query = query;
	}

	@Id
	@Column(name = "idloging", unique = true, nullable = false)
	public int getIdloging() {
		return this.idloging;
	}

	public void setIdloging(int idloging) {
		this.idloging = idloging;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_username", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "deviceId", length = 45)
	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "deviceNumber", length = 45)
	public String getDeviceNumber() {
		return this.deviceNumber;
	}

	public void setDeviceNumber(String deviceNumber) {
		this.deviceNumber = deviceNumber;
	}

	@Column(name = "deviceEmail", length = 45)
	public String getDeviceEmail() {
		return this.deviceEmail;
	}

	public void setDeviceEmail(String deviceEmail) {
		this.deviceEmail = deviceEmail;
	}

	@Column(name = "deviceLocation", length = 45)
	public String getDeviceLocation() {
		return this.deviceLocation;
	}

	public void setDeviceLocation(String deviceLocation) {
		this.deviceLocation = deviceLocation;
	}

	@Column(name = "query", length = 45)
	public String getQuery() {
		return this.query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

}
