package com.last.year.project.bean;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "searchy")
public class User implements java.io.Serializable {

	private String username;
	private String password;
	private String email;
	private String deviceId;
	private Set<Geofencing> geofencings = new HashSet<Geofencing>(0);
	private Set<Loging> logings = new HashSet<Loging>(0);

	public User() {
	}

	public User(String username) {
		this.username = username;
	}

	public User(String username, String password, String email,
			String deviceId, Set<Geofencing> geofencings, Set<Loging> logings) {
		this.username = username;
		this.password = password;
		this.email = email;
		this.deviceId = deviceId;
		this.geofencings = geofencings;
		this.logings = logings;
	}

	@Id
	@Column(name = "username", unique = true, nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "deviceId", length = 45)
	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Geofencing> getGeofencings() {
		return this.geofencings;
	}

	public void setGeofencings(Set<Geofencing> geofencings) {
		this.geofencings = geofencings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Loging> getLogings() {
		return this.logings;
	}

	public void setLogings(Set<Loging> logings) {
		this.logings = logings;
	}

}
